---
- name: Install wordpress on CentOS 7 
  gather_facts: no 
  hosts: 18.203.162.115
  become: true
  become_method: sudo      
  tasks: 
    - name: Install httpd
      package: 
        name: "{{ item }}"
        state: latest
      with_items:
        - epel-release
        - wget
        - httpd
        - php
        - mariadb-server
        - mysql
        - unzip
        - elinks
        - php-mysql
        - php-gd 
      ignore_errors: yes 
  

    - name: Download wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz 
        dest: /tmp/

    - name: Unzip wordpress
      unarchive: 
        src: /tmp/wordpress-5.4.tar.gz
        dest: /var/www/html/
        remote_src: yes 

    - name: move files to html directory
      shell: "sudo mv /var/www/html/wordpress/*  /var/www/html"
      ignore_errors: yes 

    - name: Restart apache 
      systemd: 
        name: httpd 
        state: restarted 
        enabled: yes 
      ignore_errors: yes 

    - name: Create user Bob
      user:
        name: Bob
        generate_ssh_key: yes

    - name: Create user Lisa
      user:
        name: Ben
        generate_ssh_key: yes

    - name: Create user Lisa
      user:
        name: Lisa
        generate_ssh_key: yes

    - name: Create user Katty
      user:
        name: Katty
        generate_ssh_key: yes

    - name: Route53 a record
      route53:
        state: "present"
        zone: "devops5577.com"
        record: "wordpress.devops5577.com"
        type: A
        ttl: 7200
        value: "18.203.162.115"
  
