---
- name: Installs wordpress & Route 53 config
  hosts: 18.130.223.39
  become: yes
  become_method: sudo
  tasks:
    - name: Install httpd packages
      package:
        name: "{{item}}"
        state: latest
      with_items:
       - yum_utils
       - epel-release
       - wget 
       - unzip
       - mariadb-server
       - httpd
       - php
       - php72
       - php php-mysql
       - mysql
      ignore_errors: true

  
    - name: Install epel-release
      shell: "sudo yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y"
    - name: Enable config manager 
      shell: "sudo yum-config-manager --enable remi-php72"
    - name : update httpd PHP 
      shell: "sudo yum install httpd php php-common php-opcache php-mcrypt php-cli php-gd php-curl php-mysql mysql -y" 


    - name: Download wordpress
      get_url:
        url: https://wordpress.org/wordpress-5.2.1.tar.gz
        dest: /tmp/

    - name: Unzip wordpres file
      unarchive:
        src: /tmp/latest.tar.gz    
        dest: "/var/www/html"
        remote_src: yes
      become: yes
      become_method: sudo

    - name: Move files to html folder
      shell: "mv /var/www/html/wordpress/* /var/www/html"
      become: yes
      become_method: sudo
      ignore_errors: yes

    - name: Restart httpd
      systemd:
        name: httpd
        state: restarted  
        enabled: yes
      become: yes
      become_method: sudo

    - name: Create user Bob
      user:
        name: Bob
        generate_ssh_key: yes

    - name: Create user Lisa
      user:
        name: Ben
        generate_ssh_key: yes

    - name: Create user Lisa
      user:
        name: Lisa
        generate_ssh_key: yes

    - name: Create 1 user Katty
      user:
        name: Katty
        generate_ssh_key: yes


  